_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-x86_64
features:
    value: SIFT
model:
    value: xgboost
n_clusters:
    value: 256
num_dades:
    value: 300
num_directoris:
    value: 5
test_size:
    value: 0.2
val_size:
    value: 0
