_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
features:
    value: SIFT
model:
    value: logistic
n_clusters:
    value: 32
num_dades:
    value: 5000
num_directoris:
    value: 5
test_size:
    value: 0.2
val_size:
    value: 0
